server:
  port: 8080
spring:
  profiles:
    active: '@profiles.active@'
  datasource:
    url: jdbc:postgresql://localhost:5432/forge_dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: GMT+8
