server:
  port: 8080
spring:
  application:
    name: forge-admin
  profiles:
    active: '@profiles.active@'
  datasource:
    url: jdbc:postgresql://8.134.120.64:5432/forge_dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 #最大连接数
      minimum-idle: 5 #最小空闲连接数
      idle-timeout: 60000 #空闲连接超时时间（ms）
      max-lifetime: 1800000 #连接最大生命周期（ms）
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: GMT+8
#xxl:
#  job:
#    admin-addresses: http://127.0.0.1:8020/xxl-job-admin
#    access-token: default_token
#    appname: forge-amazon-ads
#    address:
#    ip:
#    port: 0
#    logpath: /data/applogs/xxl-job/jobhandler
#    logretentiondays: 30
